"""Browser-generated case review export for mobile import.

Produces a self-contained JSON document that a mobile client stores as an OPAQUE,
read-only review: it carries the review tier, unresolved data gaps, finding
counts, and the CBCT/root-bone verdicts, plus an explicit edit-lock saying the
plan can only be edited in the full browser engine. Mobile never re-plans from
this; it displays it. A handoff descriptor (open URL / deep link / QR payload)
lets the same local or hosted case be reopened on a device.
"""

from __future__ import annotations

from collections import Counter
from datetime import UTC, datetime
from typing import Any
from urllib.parse import quote, urlencode, urlsplit, urlunsplit

from orthoplan import __version__
from orthoplan.api import evaluate_plan
from orthoplan.evaluation.rules.root_bone import root_bone_review
from orthoplan.hashing import canonical_json, sha256_text
from orthoplan.io.serialization import plan_to_json
from orthoplan.model.plan import TreatmentPlan
from orthoplan.model.review_tier import (
    cbct_status,
    review_tier_info,
    unresolved_surface_gaps,
)

CASE_REVIEW_SCHEMA = "orthoplan-case-review-v1"
DEEP_LINK_SCHEME = "orthoplan"


def _safe_base_url(base_url: str | None) -> str | None:
    if not base_url:
        return None
    parsed = urlsplit(base_url.strip())
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        return None
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path.rstrip("/"), "", ""))


def build_case_handoff(case_id: str, *, base_url: str | None = None) -> dict[str, Any]:
    """Link/deep-link/QR payload for reopening a case on another device."""

    safe_base = _safe_base_url(base_url)
    encoded_case_id = quote(case_id, safe="")
    open_url = f"{safe_base}/?{urlencode({'case': case_id})}" if safe_base else None
    deep_link = f"{DEEP_LINK_SCHEME}://case/{encoded_case_id}"
    return {
        "case_id": case_id,
        "open_url": open_url,
        "deep_link": deep_link,
        # What a QR generator should encode: prefer the hosted URL, else the deep link.
        "qr_payload": open_url or deep_link,
    }


def build_case_review_export(
    plan: TreatmentPlan,
    *,
    case_id: str | None = None,
    base_url: str | None = None,
    created_at: datetime | None = None,
) -> dict[str, Any]:
    """Build the opaque, read-only case review a mobile client can import."""

    evaluation = evaluate_plan(plan)
    tier = review_tier_info(plan)
    counts = Counter(finding["severity"] for finding in evaluation["findings"])
    resolved_case_id = case_id or plan.id
    plan_payload = plan_to_json(plan, indent=None)

    review = {
        "schema": CASE_REVIEW_SCHEMA,
        "kind": "stored-review",
        "engine": {"name": "orthoplan", "version": __version__},
        "case_id": resolved_case_id,
        "plan_id": plan.id,
        "title": plan.title,
        "created_at": (created_at or datetime.now(UTC)).isoformat(),
        "review_tier": tier.model_dump(mode="json"),
        "unresolved_data_gaps": unresolved_surface_gaps(plan),
        "data_gaps": evaluation["data_gaps"],
        "cbct_status": cbct_status(plan).value,
        "root_bone_review": {"verdict": root_bone_review(plan).verdict.value},
        "findings_summary": {
            "total": len(evaluation["findings"]),
            "by_severity": dict(counts),
        },
        # Mobile shows this as an edit-lock: a case review is generated by the
        # full browser engine and imported read-only.
        "editable": {
            "in_mobile": False,
            "requires_browser_engine": True,
            "reason": (
                "Case reviews are generated by the full browser engine and imported "
                "on mobile as read-only stored reviews."
            ),
        },
        "handoff": build_case_handoff(resolved_case_id, base_url=base_url),
        "plan_sha256": sha256_text(plan_payload),
    }
    review["review_sha256"] = sha256_text(canonical_json(case_review_digest_payload(review)))
    return review


def case_review_digest_payload(review: dict[str, Any]) -> dict[str, Any]:
    """The verifiable review body: all fields except the digest itself."""

    payload = dict(review)
    payload.pop("review_sha256", None)
    return payload


def case_review_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Validate a plan payload and build its case review export. Never raises."""

    from pydantic import ValidationError

    try:
        plan = TreatmentPlan.model_validate(payload.get("plan"))
    except ValidationError as exc:
        return {
            "ok": False,
            "errors": [
                ".".join(str(p) for p in item.get("loc", ())) + ": " + item.get("msg", "invalid")
                for item in exc.errors()
            ],
        }
    base_url = payload.get("base_url") if isinstance(payload.get("base_url"), str) else None
    case_id = payload.get("case_id") if isinstance(payload.get("case_id"), str) else None
    return {"ok": True, "review": build_case_review_export(plan, case_id=case_id, base_url=base_url)}
