#!/usr/bin/env python3
"""Generate app/mobile glossary targets from shared/glossary.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "glossary.json"
WEB = ROOT / "ui" / "glossary.js"
IOS = ROOT / "mobile" / "ios" / "App" / "Screens.swift"
ANDROID = ROOT / "mobile" / "android" / "app" / "src" / "main" / "kotlin" / "com" / "opensourceortho" / "lite" / "LiteScreens.kt"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    terms = _load_terms()
    targets = {
        WEB: _web(terms),
        IOS: _replace(IOS.read_text(encoding="utf-8"), _ios_block(terms)),
        ANDROID: _replace(ANDROID.read_text(encoding="utf-8"), _android_block(terms)),
    }
    stale = [path for path, content in targets.items() if path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            for path in stale:
                print(f"stale glossary target: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    for path, content in targets.items():
        path.write_text(content, encoding="utf-8")
    return 0


def _load_terms() -> list[dict[str, str]]:
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(raw, list) or not raw:
        raise ValueError("glossary must be a non-empty list")
    for item in raw:
        if not isinstance(item.get("term"), str) or not isinstance(item.get("definition"), str):
            raise ValueError("each glossary item needs term and definition strings")
    return raw


def _web(terms: list[dict[str, str]]) -> str:
    lines = [
        "// Generated by tools/sync_glossary.py from shared/glossary.json.",
        "// Edit the JSON source, then run the sync tool.",
        "",
        "export const glossaryTerms = [",
    ]
    for item in terms:
        lines.extend([
            "  {",
            f"    term: {_js(item['term'])},",
            f"    definition: {_js(item['definition'])},",
            "  },",
        ])
    lines.append("];")
    return "\n".join(lines) + "\n"


def _ios_block(terms: list[dict[str, str]]) -> str:
    lines = ["    // BEGIN GENERATED GLOSSARY TERMS", "    private let terms = ["]
    for item in terms:
        lines.append(f"        ({_swift(item['term'])}, {_swift(item['definition'])}),")
    lines.extend(["    ]", "    // END GENERATED GLOSSARY TERMS"])
    return "\n".join(lines)


def _android_block(terms: list[dict[str, str]]) -> str:
    lines = ["// BEGIN GENERATED GLOSSARY TERMS", "private val fullGlossaryTerms = listOf("]
    for item in terms:
        lines.append(f"    {_kotlin(item['term'])} to {_kotlin(item['definition'])},")
    lines.extend([")", "// END GENERATED GLOSSARY TERMS"])
    return "\n".join(lines)


def _replace(text: str, block: str) -> str:
    pattern = re.compile(
        r"(?ms)^([ \t]*// BEGIN GENERATED GLOSSARY TERMS\n).*?^([ \t]*// END GENERATED GLOSSARY TERMS)"
    )
    next_text, count = pattern.subn(block, text)
    if count != 1:
        raise ValueError("expected exactly one generated glossary block")
    return next_text


def _js(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _swift(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _kotlin(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


if __name__ == "__main__":
    raise SystemExit(main())
